### ISSUE TITLE
Tymoji Symbol

### ISSUE THREAD

**Issue by joker314** [Tymewalk/Tymoji#15]
We currently have lots of tymojis, but in the directory we are storing them, there is no Tymoji logo. This isn't required but would be nice, because I'm working on something for Tymoji: next to the Scratch emoji dropdown, I am creating a Tymoji one, but wasn't sure whether to use the `¬slight_smile¬ tymoji or the Tymoji logo (I cannot make a tilda on this keyboard).

It is pretty easy to add the dropdown, because Scratch uses a third party software to do it, so it is just a few method calls

**Comment by joker314** [comment]
See my PR to understand what I'm talking about

**Comment by herohamp** [comment]
There is one issue with the drop downs! It creates a [scratchblocks][/scratchblocks]

**Comment by joker314** [comment]
See my PR I wrote about this and can't figure out why :/

**Comment by joker314** [comment]
But in my timezone I should go to bed

**Comment by Tymewalk** [comment]
There's no Tymoji logo, so feel free to use whatever smiley you like. :sa:

**Comment by joker314** [comment]
Closing as this is resolved
