### ISSUE TITLE
Tymoji messes with "Add to backpack" [IMPORTANT]

### ISSUE THREAD

**Issue by joker314** [Tymewalk/Tymoji#19]
With Tymoji, users cannot use the "Add to backpack" button, added to Scratch a few days ago, together with the update to scratchblocks3 and the redesign of the search page (preventing me from finding it :/)

I am already looking in to it, but I thought you should all know.

-jokebookservice1

**Comment by Tymewalk** [comment]
Closing as that feature has been removed.

However, innerHTML is still a bad idea, so I've opened a specific issue over at #23.

**Comment by joker314** [comment]
kk
