### ISSUE TITLE
Not all of the twitter emojis show up?

### ISSUE THREAD

**Issue by CosmicWebServices** [Tymewalk/Tymoji#20]

**Comment by CosmicWebServices** [comment]
![screen shot 2016-08-31 at 2 40 31 pm](https://cloud.githubusercontent.com/assets/10731781/18141779/e69d3a2a-6f88-11e6-91d9-7884852359c5.png)

**Comment by Tymewalk** [comment]
This could be due to a glitch, or it could be due to Twitter not supporting some emojis.

I'm looking into this now.

**Comment by CosmicWebServices** [comment]
thx

**Comment by Tymewalk** [comment]
I see them as missing images too. Firefox 48.

This is probably due to the thing a while back where Twitter was missing some emojis. Updating to a different URL for Twitter should work.
