### ISSUE TITLE
Tymoji Settings aren't in a good location

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/Tymoji#7]
The bottom of the page isn't a very good place to put the settings.

**Comment by herohamp** [comment]
top?

**Comment by Tymewalk** [comment]
@herohamp Possibly. I was also considering in Account Settings (just run the emoji filter on forums and the account settings on that page).

**Comment by herohamp** [comment]
I have an Idea!

**Comment by Tymewalk** [comment]
@herohamp OK. What is it?

**Comment by herohamp** [comment]
ok. I made a pr check it out!

**Comment by Dylan5797** [comment]
You should close since my PR added a tab to the account settings page.

**Comment by Tymewalk** [comment]
@Dylan5797 It looks like it was merged.

For some reason I can't access the menu on Firefox? I see it, but when I click it it does nothing.

**Comment by herohamp** [comment]
Hmm. I have tested on chrome, safari, tor, and edge and it works

**Comment by Dylan5797** [comment]
@Tymewalk Oh no, using innerHTML wrecks event bindings and listeners on certain platforms. Tymoji should really only target text nodes...

**Comment by Tymewalk** [comment]
@herohamp Ah, darn. It looks like Firefox may just not like it :disappointed: 
@Dylan5797 Could that be my problem?

**Comment by Tymewalk** [comment]
Clarifying, I'm using Firefox 47.0 on Linux.
Can someone take screenshots of what it's supposed to look like and show me?

**Comment by Tymewalk** [comment]
Found the problem. The console says `ReferenceError: tymojiSettings is not defined`

There's a missing `var` before `tymojiSettings` but adding it doesn't seem to fix the problem.

**Comment by Tymewalk** [comment]
Manually going to https://scratch.mit.edu/accounts/settings/#tymojiSettings works! The problem is that it does not set the hash properly.

**Comment by Tymewalk** [comment]
What a silly mistake.

I forgot that any quotes would ALSO have to be escaped in the `href` attribute, too. That fixes the button.

**Comment by Tymewalk** [comment]
It STILL refuses to believe that any of the functions are there when the button is clicked.

Probably because they're part of the userscript, though. Working on fixing that.

**Comment by Tymewalk** [comment]
Finally. I got around it by labelling the `<li>` with an ID and setting `element.onclick` from Greasemonkey.

There are probably several things that can be done much better, but for now it's a start.

@Dylan5797, thank you for your awesome new menu! It looks really awesome.

Closing as we have a better location and this is now visible to users. Please make new issues for any other problems.
